name: AWS Lambda CICD
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3  
      - name: Build with Gradle
        run:  TechChallengeFiapLambda/./gradlew build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create AWS Lambda Function
        run: |
          aws lambda create-function --function-name TechChallengeLambdaFunction --runtime java21 --handler com.postech.techchallenge.PostHandler::handleRequest --role arn:aws:iam::891377229627:role/lambda-ex --zip-file fileb://target/lambda-basic-1.0-SNAPSHOT.jar
        continue-on-error: true  
      - name: Update Lambda Function    
        run: aws lambda update-function-code --function-name TechChallengeLambdaFunction --zip-file fileb://target/lambda-basic-1.0-SNAPSHOT.jar
