name: AWS Lambda CICD
'on':
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build with Gradle
        working-directory: ./TechChallengeFiapLambda
        run: ./gradlew build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: us-east-1
      - name: Sam Build
        run: sam build --use-container
      - name: Sam Dploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name tech-challenge-fiap-lambda --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-pq38cxh0oio0 --capabilities CAPABILITY_IAM --region us-east-1
